### ISSUE TITLE
String encoding issues cause difference in bytes from Python version 

### ISSUE THREAD

**Issue by ghost** [fuzeman/rencode-sharp#6]
Placeholder issue, sorry. I thought I'd worked this one out but I'm not sure. 

Basically I get 0xc3 as the first byte rather than 0xc4 when encoding. 

Will investigate further, but I think it may be the Util.Join function.

**Comment by snargledorf** [comment]
When sending a string created by this library to python, you can't use the built in .NET methods (Encoding.GetBytes). 

Instead you should convert each char in the string to a byte, and vise versa.

Ex.

``` csharp
byte[] bytes = rencodedString.Select(Convert.ToByte).ToArray();
rencodedString = string.Concat(bytes.Select(Convert.ToChar));
```

**Comment by ghost** [comment]
It only took me three months to understand the ramifications of this. Thanks - my code now works.
